package sk.yss.textprocessor.tpinitializer;

import static sk.yss.textprocessor.utilities.connectors.DatabaseConnectionCloser.close;
import static sk.yss.textprocessor.utilities.connectors.DatabaseConnector.getConnection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import sk.yss.textprocessor.utilities.UUIDProcessor;

public class RunTpInitializer {

	private static final Logger logger = LogManager.getLogger(RunTpInitializer.class);

	public static int insertUrlToDatabase(String uuid, String url) {

		logger.debug("Record with url='" + url + "', uuid='" + uuid + "' will be inserted to database.");

		Connection connection = getConnection();
		PreparedStatement ps = null;
		ResultSet retrievedId = null;

		int autoGeneratedID = -1;

		try {
			ps = connection.prepareStatement("INSERT INTO web_pages (uuid, url) VALUES (?, ?)", Statement.RETURN_GENERATED_KEYS);
			ps.setString(1, uuid);
			ps.setString(2, url);
			ps.executeUpdate();

			retrievedId = ps.getGeneratedKeys();
			retrievedId.next();
			autoGeneratedID = retrievedId.getInt(1);

			logger.debug("Record with id='" + autoGeneratedID + "', url='" + url + "', uuid='" + uuid + "' was inserted to database.");

		} catch (SQLException e) {
			logger.error("SQLException: " + e.getMessage() + "; SQL state='" + e.getSQLState() + "'", e);
		} finally {
			close(retrievedId);
			close(ps);
		}

		return autoGeneratedID;
	}

	private static String process(String url) {
		String uuid = UUIDProcessor.generateUuid();
		insertUrlToDatabase(uuid, url);
		return uuid;
	}

	public static String run(String url) {
		return process(url);
	}

	public static void main(String[] args) {

		if (args != null && args.length == 2 && args[0].equals("-uuid") && StringUtils.isNotBlank(args[1])) {
			logger.info("Valid number of parameters. Entered url='" + args[1] + "' will be processed.");
			run(args[1]);
		} else {
			logger.error("Invalid number of parameters! Use: -url url_for_processing");
		}
	}
}
