package sk.yss.textprocessor.helper;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import sk.yss.textprocessor.configuration.helper.DatabaseConnector;

public class DatabaseConnectorTest {

	private static final Logger logger = LoggerFactory.getLogger(DatabaseConnectorTest.class);

	@Test
	public void testConnection() {
		Connection connection = DatabaseConnector.getConnection();
		Assertions.assertNotNull(connection);
		DatabaseConnector.close(connection);
	}

	@Test
	public void testInsert() {
		Connection connection = DatabaseConnector.getConnection();
		PreparedStatement ps = null;
		ResultSet rs = null;

		try {
			ps = connection.prepareStatement("INSERT INTO test (small_text) VALUES (?)", Statement.RETURN_GENERATED_KEYS);
			ps.setString(1, ("insert from test " + System.currentTimeMillis()));
			ps.executeUpdate();

			rs = ps.getGeneratedKeys();

			if (rs != null && rs.next()) {
				int autoGeneratedID = rs.getInt(1);
				logger.info("Retrieved id='" + autoGeneratedID + "'");
			} else {
				logger.error("Problem with retrieving id of inserted record!");
			}
		} catch (SQLException e) {
			logger.error("SQLException: " + e.getMessage() + "; SQL state='" + e.getSQLState() + "'", e);
		} finally {
			DatabaseConnector.close(rs);
			DatabaseConnector.close(ps);
			DatabaseConnector.close(connection);
		}
	}
}
